defaults:
  - _self_
_target_: transformers.GPT2Config
n_layer: 12
n_embd: 768
n_head: 12
n_ctx: 1024
n_positions: 1024
# it would be nice to infer this automatically from a tokenizer vocab, but doing so
# would require instantiating the tokenizer, which is not possible in the config
# in other words, would lose the maximal dependency injection that we currently have
vocab_size: 50002

