name: lm-training
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.9.*
  - pip=23.*
  - black
  - mypy
  - pytorch=2.*
  - transformers=4.*
  - accelerate
  - sentencepiece=0.*
  - librosa=0.* # can remove if audio processing is not needed
  - pysoundfile>=0.12.1 # can remove if audio processing is not needed
  - hydra-core=1.*
