name: lm-training-gpu
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python>=3.9.*
  - pip=23.*
  - black
  - mypy
  - pytorch=2.*
  - pytorch-cuda=11.*
  - transformers=4.*
  - accelerate
  - hydra
