defaults:
  - /train-brainscore
dataset:
  path: wikimedia/wikipedia
  name: 20231101.en
data:
  load_disk: true
  train_loc: models/data/english_wiki/train
  eval_loc: models/data/english_wiki/eval
tokenizer:
  tokenizer_file: models/tokenizer/brainscore-bpe-english.json 
training_args:
  report_to: wandb
  output_dir: models/wandb/english
hydra:
  job:
    env_set:
      WANDB_PROJECT: brainscore-english
      WANDB_LOG_MODEL: checkpoint
      WANDB_WATCH: all
